//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalAutomation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    


    public partial class clinicalSysdbEntities : DbContext
    {
        public clinicalSysdbEntities()
            : base("name=clinicalSysdbEntities")
        {
            this.Configuration.LazyLoadingEnabled = true;
        }
           
        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chemist> chemists { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<physician> physicians { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
    }
}
