//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class physician
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public physician()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int physicianID { get; set; }
        public string name { get; set; }
        public string Specialisation { get; set; }
        public string contact { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public int regNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
