//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int productID { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public string stock { get; set; }
        public System.DateTime expiry { get; set; }
        public string category { get; set; }
    }
}
